version: '3.8'
services:
  server:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code 


  client:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app             