FROM python:3.9
WORKDIR /code
RUN pip3 install fastapi uvicorn
COPY ./backend /code/
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]

FROM node:alpine
WORKDIR /app
COPY ./frontend /app/
RUN npm i
CMD ["npm", "run", "start"]


